# Generated by Django 3.1.4 on 2021-02-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('date', models.CharField(max_length=80)),
                ('drop', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=80)),
                ('msg1', models.CharField(max_length=500)),
            ],
        ),
    ]
