# Generated by Django 3.1.4 on 2021-03-02 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='dateajax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateaj', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=80)),
                ('ddept', models.CharField(max_length=80)),
                ('dphone', models.CharField(max_length=80)),
                ('demail', models.CharField(max_length=80)),
                ('dimage', models.ImageField(upload_to='portfolio/images')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('ntitle', models.CharField(max_length=80)),
                ('ndesc', models.CharField(max_length=80)),
                ('aname', models.CharField(max_length=80)),
                ('apos', models.CharField(max_length=80)),
                ('aimg', models.ImageField(upload_to='portfolio/images')),
            ],
        ),
        migrations.CreateModel(
            name='timeslot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='timeajax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeaj', models.CharField(max_length=80)),
                ('status', models.IntegerField(default=0)),
                ('dateajax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.dateajax')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('date', models.CharField(max_length=80)),
                ('drop', models.CharField(max_length=80)),
                ('time', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=80)),
                ('msg1', models.CharField(max_length=500)),
                ('status', models.IntegerField(default=0)),
                ('dateaj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.dateajax')),
                ('timeaj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.timeajax')),
            ],
        ),
    ]
