# Generated by Django 3.1.4 on 2021-03-03 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dates',
        ),
        migrations.DeleteModel(
            name='timeslot',
        ),
    ]
