# Generated by Django 3.1.4 on 2021-02-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=80)),
                ('ddept', models.CharField(max_length=80)),
                ('dphone', models.CharField(max_length=80)),
                ('demail', models.CharField(max_length=80)),
                ('dimage', models.ImageField(upload_to='portfolio/images')),
            ],
        ),
    ]
