# Generated by Django 3.1.4 on 2021-02-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_doctors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='id',
        ),
        migrations.AddField(
            model_name='doctors',
            name='doc_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
