# Generated by Django 3.1.4 on 2021-02-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('ntitle', models.CharField(max_length=80)),
                ('ndesc', models.CharField(max_length=80)),
                ('aname', models.CharField(max_length=80)),
                ('apos', models.CharField(max_length=80)),
                ('aimg', models.ImageField(upload_to='portfolio/images')),
            ],
        ),
    ]
