# Generated by Django 3.1.4 on 2021-02-07 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_form_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='time',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
    ]
