# Generated by Django 3.1.4 on 2021-02-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_form_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='time',
            field=models.TimeField(),
        ),
    ]
