# Generated by Django 3.1.4 on 2021-02-07 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20210207_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='status',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
    ]
