# Generated by Django 3.1.4 on 2021-02-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20210208_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='date',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='form',
            name='time',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='date',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='time',
            field=models.CharField(max_length=80),
        ),
    ]
